feat: modules create at start
InsertKoinIO/koin-annotations pull request #106
Opened 2023-12-22 19:35 UTC by ghasemdev

2023-12-23 10:35 UTC, ghasemdev commented
@arnaudgiuliani

2024-01-30 10:20 UTC, arnaudgiuliani commented
Super interesting thanks 👍 Let me check your PR

2024-01-30 12:36 UTC, ghasemdev commented
> Super interesting thanks 👍 Let me check your PR

thanks

2024-01-30 16:12 UTC, arnaudgiuliani commented on compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/verify/KoinConfigVerification.kt
> +)
same comment here :) need to remove this, as it's already part of another PR

2024-01-30 16:13 UTC, arnaudgiuliani requested changes
Just remove the ignored part

2024-02-15 15:04 UTC, arnaudgiuliani commented
Need to prepare branch for 1.4.0, and I'll merge it

2024-02-15 15:05 UTC, arnaudgiuliani approved these changes

2024-06-06 14:47 UTC, merged